version: "3.6"
services: 
  api:
    build: .
    ports: 
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=8b35b78b289bf9888a06b7f7e0ab53d0da17daef9b27c92a6ddfc20993dd3fb6
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: