"""auto-votes

Revision ID: 8b138666b6b1
Revises: 9d07328862a0
Create Date: 2023-05-20 19:33:31.265124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b138666b6b1'
down_revision = '9d07328862a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
                        sa.Column('user_id', sa.Integer(), nullable=False),
                        sa.Column('post_id', sa.Integer(), nullable=False),
                        sa.ForeignKeyConstraint(['post_id'], ['posts.id'] , ondelete='CASCADE'),
                        sa.ForeignKeyConstraint(['user_id'], ['users.id'] , ondelete='CASCADE'),
                        sa.PrimaryKeyConstraint( 'user_id', 'post_id')
                        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
